# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 22.10.0  # The latest version of Black
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  # The latest version of flake8
    hooks:
      - id: flake8
        args: ["--max-line-length=255"]  # Match Black's line length
        additional_dependencies: ['flake8-bugbear']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1  # Latest mypy version
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
